spring:
  datasource:
    url: jdbc:h2:mem:testdb

#    driver-class-name: org.h2.Driver
  #    driver-class-name: org.h2.Driver
#logging:
#  level:
#    root: DEBUG



#  h2:
#    console:
#      enabled: true
#      path: /h2