DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT auto_increment PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID          BIGINT auto_increment PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT auto_increment PRIMARY KEY,
    TITLE     VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);

-- DROP TABLE IF EXISTS BOOK_AUTHOR;
-- CREATE TABLE BOOKS_AUTHORS(
-- BOOK_ID BIGINT NOT NULL,
-- AUTHOR_ID BIGINT NOT NULL,
-- PRIMARY KEY (BOOK_ID, AUTHOR_ID),
-- FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
-- FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
-- );
--
-- DROP TABLE IF EXISTS BOOKS_GENRES;
-- CREATE TABLE BOOKS_GENRES(
-- BOOK_ID BIGINT NOT NULL,
-- GENRE_ID BIGINT NOT NULL,
-- PRIMARY KEY (BOOK_ID, GENRE_ID),
-- FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
-- FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
-- );